// Generates src/graphite/icons.gleam from pixelarticons (MIT, Gerrit Halfmann).
// Add an icon by appending its file name (node_modules/pixelarticons/svg/)
// below, then run `node scripts/icons.mjs`.

import { readFileSync, writeFileSync } from "node:fs";

const ICONS = ["arrow-left", "book-open", "download", "notebook", "printer", "reload", "shuffle"];

const variant = (name) =>
  name.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase());

const cases = ICONS.map((name) => {
  const svg = readFileSync(`node_modules/pixelarticons/svg/${name}.svg`, "utf8");
  const body = svg.replace(/^<svg[^>]*>|<\/svg>\s*$/g, "").trim();
  const paths = [...body.matchAll(/<path d="([^"]+)"\s*\/>/g)];
  if (body.replace(/<path d="[^"]+"\s*\/>/g, "").trim() !== "") {
    throw new Error(`${name}.svg has elements other than <path>`);
  }
  return `    ${variant(name)} ->\n      "${paths.map((m) => m[1]).join("")}"`;
});

writeFileSync(
  "src/graphite/icons.gleam",
  `//// Pixel icons from pixelarticons (MIT, Gerrit Halfmann), drawn on a
//// 24×24 grid. Generated by scripts/icons.mjs; do not edit by hand.

pub type Icon {
${ICONS.map((n) => `  ${variant(n)}`).join("\n")}
}

/// SVG path data for a 24×24 viewBox, filled with currentColor.
pub fn path(icon: Icon) -> String {
  case icon {
${cases.join("\n")}
  }
}
`,
);
