//// Pixel icons from pixelarticons (MIT, Gerrit Halfmann), drawn on a
//// 24×24 grid. Generated by scripts/icons.mjs; do not edit by hand.

pub type Icon {
  ArrowLeft
  BookOpen
  Download
  Notebook
  Printer
  Reload
  Shuffle
}

/// SVG path data for a 24×24 viewBox, filled with currentColor.
pub fn path(icon: Icon) -> String {
  case icon {
    ArrowLeft ->
      "M20 11v2H4v-2zM8 13v2H6v-2zm2 2v2H8v-2zm2 2v2h-2v-2zm-4-6V9H6v2zM10 15V7H8v8zm2 2V5h-2v12z"
    BookOpen ->
      "M2 3h9v2H2zM0 19h11v2H0zM13 3h9v2h-9zm0 16h11v2H13zM11 5h2v18h-2zM0 5h2v14H0zm22 0h2v14h-2zm-7 2h5v2h-5zm0 4h5v2h-5zm0 4h2v2h-2z"
    Download ->
      "M21 15v4h-2v-4zm-2 4v2H5v-2zM5 15v4H3v-4zm8-12v14h-2V3zM7 11v2h10v-2zm2 2v2h2v-2zm4 0v2h2v-2zM15 11v2h2v-2z"
    Notebook ->
      "M6 2h14v2H6zm0 18h14v2H6zM20 4h2v16h-2zM4 4h2v16H4zM2 7h6v2H2zm0 4h6v2H2zm0 4h6v2H2zM16 4h2v16h-2z"
    Printer ->
      "M6 4h2v4H6zm2-2h8v2H8zm8 2h2v4h-2zM4 6h16v2H4zM2 8h2v10H2zm2 10h2v2H4zm2-4h12v2H6zM6 14h2v8H6zm2 6h8v2H8zm8-6h2v8h-2zm2 4h2v2h-2zm2-10h2v10h-2zm-4 2h2v2h-2zm-4 0h2v2h-2z"
    Reload ->
      "M16 4h2v6h-2zm-2-2h2v2h-2zm0 2h2v8h-2zM4 8H2v5h2zM4 6h16v2H4zm4 14H6v-6h2zm2 2H8v-2h2zm0-2H8v-8h2zm10-4h2v-5h-2zM20 18H4v-2h16z"
    Shuffle ->
      "M10 19H2v-2h8v2Zm12 0h-8v-2h8v2Zm-10-2h-2v-6h2v6Zm6-10h2v2h2v2h-2v2h-2v2h-2v-4h-4V9h4V5h2v2ZM8 11H2V9h6v2Z"
  }
}
